name: the queer factory
favicon: null
layout_spectrum: 0.8554231310263276
typography_spectrum: 0.43123887851834297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.28768121008761227
  lightness: 0.8799690008163452
  saturation: 0.7418266956228763
  rhythmicContrast: 0.27992831938900054
purpose: []
